language: crystal

sudo: false

os:
  - osx

before_install: |
  export LLVM_CONFIG=/usr/local/opt/llvm@6/bin/llvm-config
  export PATH="/usr/local/opt/llvm@6/bin:$PATH"
before_script: |
  ls -l /usr/bin | grep llvm-config
  crystal build emeraldc.cr