language: crystal

sudo: false

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - llvm-3.9
    - libclang1-3.9
    - libllvm3.9
    - libstdc++6
    - libstdc++-4.9-dev
    - libgcc-4.9-dev
    - libobjc-4.9-dev
    - libclang-common-3.9-dev
    - llvm-3.9-runtime

script:
  - mkdir test_outputs; crystal build emeraldc.cr; crystal spec
