language: crystal

sudo: false

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.9
    packages:
    - clang-3.9
    - llvm-3.9

script:
  - mkdir test_outputs; crystal build emeraldc.cr; crystal spec
