language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t Virtual-Machine/llvm-tutorial-book .


script:
  - docker run Virtual-Machine/llvm-tutorial-book /bin/sh -c "cd /opt/llvm-tutorial; crystal spec"
