language: generic
sudo: required
dist: trusty
services:
  - docker
matrix:
  include:
    - env: ARCH=i386 ARCH_CMD=linux32
      os: linux
    - env: ARCH=x86_64 ARCH_CMD=linux64 DEPLOY=true
      os: linux
    - os: osx